alias n="nvim"
alias o="sk_open_file"
alias vim="nvim"

alias tn="tmux new -s"
alias ta="sk_tmux_attach_session"
alias tw="sk_tmux_attach_window"
alias tl="tmux ls"
alias tp="sk_tmux_switch_pane"

alias gco="git checkout"
alias g-="git checkout -"
alias gm-="git merge -"
alias gs="git status"
alias gb="sk_git_checkout_branch"
alias gbr="sk_git_checkout_branch_remote"
alias lg="lazygit"
