alias n="nvim"
alias o="fzf_open_file"
alias vim="nvim"

alias tn="tmux new -s"
alias ta="fzf_tmux_attach_session"
alias tw="fzf_tmux_attach_window"
alias tl="tmux ls"

alias gco="git checkout"
alias g-="git checkout -"
alias gm-="git merge -"
alias gs="git status"
alias gb="fzf_git_checkout_branch"
alias gbr="fzf_git_checkout_branch_remote"
alias lg="lazygit"
